// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import localFont from "next/font/local";
// import "./globals.css";
// import clsx from "clsx";

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const generalsans = localFont({
//   src: [
//     {
//       path: "../client/fonts/GeneralSans-Bold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//   ],
//   variable: "--font-generalsans",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={clsx(inter.variable, generalsans.variable, "antialiased")}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const generalsans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-generalsans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(inter.variable, generalsans.variable, "antialiased")}
      >
        {children}
      </body>
    </html>
  );
}
