import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import clsx from "clsx";
import { getGlobalSettings } from "@/data/loaders";
import { Header } from "@/components/layout/Header";
import { notFound } from "next/navigation";
import { Footer } from "@/components/layout/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const generalsans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/GeneralSans-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-generalsans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// async function loader() {
//   const { data } = await getGlobalSettings();
//   if (!data) throw new Error("Failed to fetch global settings");
//   return { header: data?.header };
// }

async function loader() {
  const { data } = await getGlobalSettings();
  console.dir(data, { depth: null });
  if (!data) notFound();
  return { header: data?.header, footer: data?.footer };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { header, footer } = await loader();
  return (
    <html lang="en">
      <body
        className={clsx(inter.variable, generalsans.variable, "antialiased")}
      >
        <Header data={header} />
        {children}
        <Footer data={footer} />
      </body>
    </html>
  );
}
